# Generated by Django 5.0 on 2023-12-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.CharField(max_length=55),
        ),
    ]
